# Generated by Django 3.1.7 on 2021-05-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=45)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.CharField(max_length=240)),
                ('existencias', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], max_length=40)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
            ],
        ),
    ]
